
disable-completely: true

excluded-regions: # Requires WorldGuard
  - spawn
  - pvp-arena

completely-disabled-message: "&cWIND_CHARGE usage is completely disabled!"
deny-message: "&cYou cannot use this item in region &e%region%&c!"
reload-message: "&aConfiguration reloaded!"
no-permission-message: "&cYou don't have permission to use this command!"
startup-message: "&aNoWindCharge has been enabled!"
shutdown-message: "&cNoWindCharge has been disabled!"
